# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |        Playbook for SAP Functional Tests (sap-automation-qa)               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts:                               localhost
  name:                                "SAP Functional Tests: - setup deployer"
  gather_facts:                        true
  vars_files:                          vars/ansible-input-api.yaml
  tasks:
    - name:                            "SAP Functional Tests: - Create Progress folder"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress"
        state:                         directory
        mode:                          0755

    - name:                            "SAP Functional Tests: - Remove sap-funtional-test flag"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress/sap-functional-tests-done"
        state:                          absent

    - name:                            SAP Functional Tests - setup directories
      become:                          true
      become_user:                     root
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        state:                         directory
        mode:                          0755
        owner:                         "{{ item.owner }}"
      loop:
        - { path: "/opt/microsoft/sap_functional_tests", owner: "{{ orchestration_ansible_user }}" }
        - { path: "{{ _workspace_directory }}/quality_assurance", owner: "{{ orchestration_ansible_user }}" }

    - name:                            "SAP Functional Tests - fetch sap-automation-qa"
      become:                          true
      become_user:                     root
      ansible.builtin.git:
        repo:                          "https://{{ github_pat }}@github.com/devanshjainms/sap-automation-qa.git"
        dest:                          "/opt/microsoft/sap_functional_tests"
        version:                       main
        clone:                         true
        single_branch:                 true
        force:                         true

- name:                                "SAP Functional DB: Tests run checks"
  ansible.builtin.import_playbook:     "/opt/microsoft/sap_functional_tests/src/playbook_00_ha_db_functional_tests.yml"
  when:                                sap_functional_test_type == "DatabaseHighAvailability"

- name:                                "SAP Functional Central Services: Tests run checks"
  ansible.builtin.import_playbook:     "/opt/microsoft/sap_functional_tests/src/playbook_00_ha_scs_functional_tests.yml"
  when:                                sap_functional_test_type == "CentralServicesHighAvailability"

- hosts:                               localhost
  name:                                "SAP Functional Tests: - Done"
  gather_facts:                        true
  vars_files:                          vars/ansible-input-api.yaml
  tasks:
    - name:                            "SAP Functional Tests: - Create sap-functional-tests-done flag"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress/sap-functional-tests-done"
        state:                         touch
        mode:                          0755
...
