# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Playbook for SAP Functional Tests (sap-automation-qa)      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:                               localhost
  name:                                "SAP Functional Tests: - setup deployer"
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml
  tasks:
    - name:                            "SAP Functional Tests: - Create Progress folder"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress"
        state:                         directory
        mode:                          0755

    - name:                            "SAP Functional Tests: - Remove sap-funtional-test flag"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress/sap-functional-tests-done"
        state:                          absent

    - name:                            "SAP Functional Tests: - setup prerequisites"
      ansible.builtin.include_role:
        name:                          "roles-misc/0.10-sap-functional-tests"
        tasks_from:                    setup.yaml

- name:                                "SAP Functional: Tests run checks"
  when:                                sap_functional_tests_type == "HA_DB_HANA_SLES"
  ansible.builtin.import_playbook:     "/opt/microsoft/sap_functional_tests/ansible/playbook_00_ha_functional_tests.yml"
  vars:
    - sap_functional_tests_type:       "{{ sap_functional_tests_type }}"

- hosts:                               localhost
  name:                                "SAP Functional Tests: - Done"
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml
  tasks:
    - name:                            "SAP Functional Tests: - Create sap-functional-tests-done flag"
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.progress/sap-functional-tests-done"
        state:                         touch
        mode:                          0755
...
# /*---------------------------------------------------------------------------8
# |                                    END                                     |
# +------------------------------------4--------------------------------------*/
