# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Setup environment to run SAP Functional Tests               |
# |                        from the Azure/sap-automation-qa                          |
# +------------------------------------4--------------------------------------*/
---

- name:                            SAP Functional Tests - setup directories
  become:                          true
  ansible.builtin.file:
    path:                          "{{ item.path }}"
    state:                         directory
    mode:                          0755
    owner:                         "{{ item.owner }}"
  loop:
    - { path: "/opt/microsoft/sap_automation_qa", owner: "{{ orchestration_ansible_user }}" }
    - { path: "{{ _workspace_directory }}/quality_assurance", owner: "{{ orchestration_ansible_user }}" }

- name:                            "SAP Functional Tests - fetch sap-automation-qa"
  become:                          true
  ansible.builtin.git:
    repo:                          "https://github.com/{{ sap_automation_qa_fork }}/sap-automation-qa.git"
    dest:                          "/opt/microsoft/sap_automation_qa"
    version:                       "{{ sap_automation_qa_branch }}"
    clone:                         true
    single_branch:                 false
    force:                         true

- name:                             "Install python3-venv system package"
  become:                           true
  ansible.builtin.package:
    name:                           python3-venv
    state:                          present

- name:                             "Create virtual environment"
  ansible.builtin.pip:
    name:                           pip
    virtualenv:                     "/opt/microsoft/sap_automation_qa/.venv"
    virtualenv_command:             python3 -m venv

- name:                             "Install python azure packages required"
  become:                           false
  ansible.builtin.pip:
    virtualenv:                     "/opt/microsoft/sap_automation_qa/.venv"
    requirements:                   "/opt/microsoft/sap_automation_qa/requirements.in"

- name:                             "Set ANSIBLE_PYTHON_INTERPRETER environment variable"
  ansible.builtin.set_fact:
    ansible_python_interpreter:     "/opt/microsoft/sap_automation_qa/.venv/bin/python3"
