# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
---

- name:                       "Get resource id of the VM using IMDS"
  ansible.builtin.uri:
    url:                      http://169.254.169.254/metadata/instance?api-version=2021-02-01
    use_proxy:                false
    headers:
      Metadata:               true
  register:                   vm_metadata

- name:                       "Check if VM is registered with recovery services vault"
  delegate_to:                localhost
  register:                   backup_container_list
  ansible.builtin.shell: |
                              az backup container list --backup-management-type AzureWorkload \
                                --resource-group {{ sap_backup_resource_group }} \
                                --vault-name {{ sap_backup_vault_name }} \
                                --output table

- name:                       "Run command to register instance with recovery services vault"
  delegate_to:                localhost
  when:                       backup_container_list.rc == 0 and
                              vm_metadata.json.compute.resourceId.split('/')[-1] not in backup_container_list.stdout
  register:                   backup_container_register
  ansible.builtin.shell: |
                              az backup container register --resource-group {{ sap_backup_resource_group }} \
                                  --vault-name {{ sap_backup_vault_name }} \
                                  --workload-type SAPHANA \
                                  --backup-management-type AzureWorkload \
                                  --resource-id {{ vm_metadata.json.compute.resourceId }}

- name:                       "Get the list of databases discovered in registration setup"
  delegate_to:                localhost
  when:
                              - backup_container_list.rc == 0
                              - backup_container_register.skipped | default(false) or
                                backup_container_register.rc | default(1) == 0
  register:                   backup_item_list
  ansible.builtin.shell: |
                              az backup protectable-item list --resource-group {{ sap_backup_resource_group }} \
                                --vault-name {{ sap_backup_vault_name }} \
                                --workload-type SAPHANA

- name:                       "Filter backups for SAP HANA databases"
  delegate_to:                localhost
  when:                       backup_item_list is defined and backup_item_list.rc == 0
  ansible.builtin.set_fact:
    backup_protectable_items: []

- name:                       "Build backup items list"
  delegate_to:                localhost
  ansible.builtin.set_fact:
    backup_protectable_items: "{{ backup_protectable_items + [{'item_name': item.name, 'server_name': item.properties.serverName}] }}"
  loop:                       "{{ backup_item_list.stdout | from_json }}"
  loop_control:
    loop_var:                 item
  when:
    - backup_item_list is defined
    - backup_item_list.rc == 0
    - item.properties.protectableItemType == 'SAPHanaDatabase'
    - item.properties.protectionState == 'NotProtected'
    - item.properties.IsProtectable == true

- name:                       "Enable backup for SAP HANA databases"
  delegate_to:                localhost
  when:                       backup_protectable_items is defined and backup_protectable_items | length > 0
  ansible.builtin.shell: |
                              az backup protection enable-for-azurewl --resource-group {{ sap_backup_resource_group }} \
                                --vault-name {{ sap_backup_vault_name }} \
                                --policy-name {{ sap_backup_policy_name }} \
                                --protectable-item-name "{{ backup_item.item_name }}"  \
                                --protectable-item-type SAPHANADatabase \
                                --server-name "{{ backup_item.server_name }}" \
                                --workload-type SAPHANA \
                                --output table
  loop:                       "{{ backup_protectable_items }}"
  loop_control:
    loop_var:                 backup_item

- name:                       "Get backup list for SAP HANA Databases have been enabled"
  delegate_to:                localhost
  when:                       backup_protectable_items is defined and backup_protectable_items | length > 0
  ansible.builtin.shell:
                              az backup item list --resource-group {{ sap_backup_resource_group }} \
                                --vault-name {{ sap_backup_vault_name }} \
                                --backup-management-type AzureWorkload \
                                --workload-type SAPHanaDatabase
  register:                   enabled_backup_items

- name:                       "Create list of enabled backup item names"
  delegate_to:                localhost
  when:                       enabled_backup_items is defined and enabled_backup_items.rc == 0
  ansible.builtin.set_fact:
    enabled_item_names:       "{{ enabled_backup_items.stdout | from_json | map(attribute='name') | list }}"

- name:                       "Validate each database is backed up"
  delegate_to:                localhost
  ansible.builtin.assert:
    that:                     backup_item.item_name in enabled_item_names
    fail_msg:                 "Database {{ backup_item.item_name }} is not protected"
    success_msg:              "Database {{ backup_item.item_name }} is protected"
  loop:                       "{{ backup_protectable_items }}"
  loop_control:
    loop_var:                 backup_item
  when:                       enabled_item_names is defined and backup_protectable_items is defined
