# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the infrastructure for SAP Backup      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              backup_configuration_name
    displayName:                       "Backup Configuration Name (ENV-REGION-LOGICAL_BACKUP_NAME-BACKUP)"
    type:                              string
    default:                           DEV-SECE-BUP01-BACKUP

  - name:                              environment
    displayName:                       Backup Environment (DEV, QA, PRD, ...)
    type:                              string
    default:                           DEV

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              test
    displayName:                       Test deployment without applying the changes
    type:                              boolean

stages:
  - stage: Deploy_SAP_Backup_Infrastructure
    condition: and(not(failed()), not(canceled()))
    variables:
      - template:                      variables/08-sap-backup-infrastructure-variables.yaml
        parameters:
          backup_configuration_name:  ${{ parameters.backup_configuration_name }}
          environment:                 ${{ parameters.environment }}
          test:                        ${{ parameters.test }}
    displayName:                       Deploy SAP Backup Infrastructure
    jobs:
      - job:                           Deploy_SAP_Backup_Infrastructure
        displayName:                   Deploy SAP Backup Infrastructure
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/08-sap-backup-infrastructure.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Deploy_SAP_Backup_Infrastructure
            env:
              ARM_CLIENT_ID:                   $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:               $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID:             $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                   $(ARM_TENANT_ID)
              ARM_USE_MSI:                     $(ARM_USE_MSI)
              AZURE_DEVOPS_EXT_PAT:            $(System.AccessToken)
              BACKUP_CONFIGURATION_FOLDERNAME: $(backup_configuration_foldername)
              CONFIG_REPO_PATH:                ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              DEPLOYER_KEYVAULT:               $(DEPLOYER_KEYVAULT)
              KEYVAULT:                        $(KEYVAULT)
              TERRAFORM_STATE_STORAGE_ACCOUNT: $(TERRAFORM_STATE_STORAGE_ACCOUNT)
              LOGON_USING_SPN:                 $(Logon_Using_SPN)
              SAP_AUTOMATION_REPO_PATH:        ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:              $(System.AccessToken)
              TEST_ONLY:                       ${{ parameters.test }}
              TF_IN_AUTOMATION:                true
              TF_LOG:                          $(TF_LOG)
              USE_MSI:                         $(Use_MSI)
              environment:                     ${{ parameters.environment }}
              VARIABLE_GROUP:                  $(variable_group)
