# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows deploys the SAP Workload Zone with GitHub Actions       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: SAP Infrastructure Deployment
run-name: SAP Infrastructure Deployment by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      sap_system:
        description: "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
        required: true
        type: string
        default: "DEV-EAUS-SAP01-X00"
      environment:
        description: "Workload Environment (DEV, QA, PRD, ...)"
        required: true
        type: string
        default: DEV"
      test:
        description: "Test the deployment without actually deploying the resources"
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  deploy_sap_system:
    name: Deploy SAP System
    environment: ${{ inputs.sap_system }}
    runs-on: self-hosted
    container:
      image: ghcr.io/devanshjainms/sap-automation:experimentalga
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy SAP system infrastructure
        run: |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/automation/03-sap-system-deployment/01-sap-system-deployment.sh
        env:
          sapSystemFolder: ${{ inputs.sap_system }}
          environment: ${{ inputs.environment }}
          sap_automation_repo_path: ${SAP_AUTOMATION_REPO_PATH}
          test: ${{ inputs.test }}
