# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows deploys the SAP Workload Zone with GitHub Actions       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: SAP Software Download
run-name: SAP Software Download by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bom_base_name:
        description: "Name of Bill of Materials (BoM)"
        required: true
        type: choice
        options:
            - S4HANA_2022_FP02_v0001ms
            - S4HANA_2021_ISS_v0001ms
            - S4HANA_2021_ISS_v0002ms
            - S4HANA_2021_FP01_v0001ms
            - S4HANA_2021_FP01_v0002ms
            - S42022SPS00_v0001ms
            - S42020SPS04_v0001ms
            - S42020SPS04_v0002ms
            - S41909SPS03_v0011ms
            - S41909SPS03_v0012ms
            - HCMT_v0002ms
            - BW4HANA2021SPS01_v0003ms
            - HANA_2_00_055_v0006ms
            - HANA_2_00_059_v0004ms
            - HANA_2_00_066_v0001ms
            - HANA_2_00_067_v0004ms
            - HANA_2_00_071_v0001ms
            - NW750_HANA_v0004ms
            - NW752SPS09_v0001ms
            - NW750SPS20_DB2_v0001ms
            - NW750_ORACLE_19_v0001ms
            - NW750_MSSQL_v0001ms
            - NW752_MSSQL_v0001ms
            - NW750SPS20_SYBASE_v0001ms
            - NW750_ORACLE_19_ASM_v0001ms
            - NW750SPS25_JAVA_v0001ms
            - ORACLE_19_00_v0003ms
            - ORACLE_19_00_ASM_v0001ms
            - NW750SPS20_DB2_v0001ms
            - DB2_UDB_11_5_v0001ms
            - ORACLE_19_00_ORA_MSID_v0002ms
            - ERP6_EHP8_WIN_MSS2019_v0001ms
            - ERP6_EHP8_WIN_MSS2016_v0001ms
            - ERP6_EHP8_LNX_DB2UDB_11_5_v0001ms
      environment:
        description: "Control Plane Environment (CTRL, MGMT)"
        required: true
        type: string
        default: "CTRL"
      region:
        description: "Control Plane (SAP Library) location code"
        required: true
        type: string
        default: "EAUS"
      extra_params:
        description: "Extra Parameters"
        type: string
        default: " "
      re_download:
        description: "Re-download the software"
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  download_sap_software:
    name: SAP software download
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    container:
      image: ghcr.io/devanshjainms/sap-automation:devanshjain-githubworkflow
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Download SAP Software
        run: |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/automation/04-sap-software-download/01-sap-software-download.sh
        env:
          environment: ${{ inputs.environment }}
          sap_automation_repo_path: ${SAP_AUTOMATION_REPO_PATH}
          bom_base_name: ${{ inputs.bom_base_name }}
          region: ${{ inputs.region }}
          re_download: ${{ inputs.re_download }}
          ExtraParams: ${{ inputs.extra_params }}