# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows performs the Software Installation with GitHub Actions  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: OS configuration and SAP installation
run-name: OS configuration and SAP installation by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      sap_system_configuration_name:
        description: "SAP System configuration name, use the following syntax: ENV-LOC-VNET-SID"
        required: true
        type: string
        default: "DEV-EAUS-SAP01-X00"
      environment:
        description: "Workload Zone Environment (DEV, PROD, TEST ...)"
        required: true
        type: string
        default: "DEV"
      bom_base_name:
        description: "Name of Bill of Materials (BoM)"
        required: true
        type: choice
        options:
            - S4HANA_2022_FP02_v0001ms
            - S4HANA_2021_ISS_v0001ms
            - S4HANA_2021_ISS_v0002ms
            - S4HANA_2021_FP01_v0001ms
            - S4HANA_2021_FP01_v0002ms
            - S42022SPS00_v0001ms
            - S42020SPS04_v0001ms
            - S42020SPS04_v0002ms
            - S41909SPS03_v0011ms
            - S41909SPS03_v0012ms
            - HCMT_v0002ms
            - BW4HANA2021SPS01_v0003ms
            - HANA_2_00_055_v0006ms
            - HANA_2_00_059_v0004ms
            - HANA_2_00_066_v0001ms
            - HANA_2_00_067_v0004ms
            - HANA_2_00_071_v0001ms
            - NW750_HANA_v0004ms
            - NW752SPS09_v0001ms
            - NW750SPS20_DB2_v0001ms
            - NW750_ORACLE_19_v0001ms
            - NW750_MSSQL_v0001ms
            - NW752_MSSQL_v0001ms
            - NW750SPS20_SYBASE_v0001ms
            - NW750_ORACLE_19_ASM_v0001ms
            - NW750SPS25_JAVA_v0001ms
            - ORACLE_19_00_v0003ms
            - ORACLE_19_00_ASM_v0001ms
            - NW750SPS20_DB2_v0001ms
            - DB2_UDB_11_5_v0001ms
            - ORACLE_19_00_ORA_MSID_v0002ms
            - ERP6_EHP8_WIN_MSS2019_v0001ms
            - ERP6_EHP8_WIN_MSS2016_v0001ms
            - ERP6_EHP8_LNX_DB2UDB_11_5_v0001ms
      extra_params:
        description: "Extra Parameters"
        type: string
        default: " "
      base_os_configuration:
        description: "Core operating system configuration"
        required: true
        type: boolean
        default: true
      sap_os_configuration:
        description: "SAP operating system configuration"
        required: true
        type: boolean
        default: true
      bom_processing:
        description: "Local software download and processing"
        required: true
        type: boolean
        default: true
      scs_installation:
        description: "SCS Installation and high availability configuration"
        required: true
        type: boolean
        default: true
      database_installation:
        description: "Database Installation"
        required: true
        type: boolean
        default: true
      db_load:
        description: "Database Load"
        required: true
        type: boolean
        default: true
      high_availability_configuration:
        description: "Database High Availability Configuration"
        required: true
        type: boolean
        default: true
      pas_installation:
        description: "Primary Application Server Installation"
        required: true
        type: boolean
        default: true
      application_server_installation:
        description: "Application Server Installation"
        required: true
        type: boolean
        default: true
      webdispatcher_installation:
        description: "Web Dispatcher Installation"
        required: true
        type: boolean
        default: true

      ascs_registration:
        description: "ASCS Registration"
        required: true
        type: boolean
        default: true
      acss_envrionment:
        description: "ACSS Prod/NonProd"
        required: true
        type: choice
        options:
            - Prod
            - NonProd
      acss_sap_product:
        description: "System Type"
        required: true
        type: choice
        options:
            - S4HANA
            - ECC
            - Other

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  download_sap_software:
    name: SAP software download
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    container:
      image: ghcr.io/devanshjainms/sap-automation:experimentalga
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Download SAP Software
        run: |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/automation/05-DB-and-SAP-installation/01-DB-and-SAP-installation.sh
        env:
          environment: ${{ inputs.environment }}
          sap_automation_repo_path: ${SAP_AUTOMATION_REPO_PATH}
          bom_base_name: ${{ inputs.bom_base_name }}
          sap_system_configuration_name: ${{ inputs.sap_system_configuration_name }}
          sap_os_configuration: ${{ inputs.sap_os_configuration }}
          base_os_configuration: ${{ inputs.base_os_configuration }}
          bom_processing: ${{ inputs.bom_processing }}
          scs_installation: ${{ inputs.scs_installation }}
          database_installation: ${{ inputs.database_installation }}
          db_load: ${{ inputs.db_load }}
          high_availability_configuration: ${{ inputs.high_availability_configuration }}
          pas_installation: ${{ inputs.pas_installation }}
          application_server_installation: ${{ inputs.application_server_installation }}
          webdispatcher_installation: ${{ inputs.webdispatcher_installation }}
          ascs_registration: ${{ inputs.ascs_registration }}
          acss_envrionment: ${{ inputs.acss_envrionment }}
          acss_sap_product: ${{ inputs.acss_sap_product }}
          config_repo_path: ${{ inputs.sap_system_configuration_name }}.tfvars
          extra_params: ${{ inputs.extra_params }}
